.TH MYPROJECT 1 "April 2025" "1.0" "User Commands"
.SH NAME
backup2mail \- Bash tool for automatically sending backups via email
.SH SYNOPSIS
.B backup2mail
[\fIOPTIONS\fR]
.SH DESCRIPTION
backup2mail is a project that automates the process of sending backups via email. It is designed to be simple and efficient, allowing users to easily configure and manage their backup tasks. The tool can be used in various environments, including personal computers and servers.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version information.
.SH EXAMPLES
.B backup2mail
\-\-run-task
.SH AUTHOR
Matthew Wasa <matheww.coding@gmail.com>
.SH LICENSE
MIT